function pErr = importPErrStoFile(filename, startRow, endRow)
%importPErrStoFile Import numeric data from a text file as a matrix.
%   pErr = importPErrStoFile(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   pErr = importPErrStoFile(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   pErr = importPErrStoFile('cmc_pErr.sto', 8, 139);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/02/08 11:36:08

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 8;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
pErr = dataset(dataArray{1:end-1}, 'VarNames', {'time','pelvistx','pelvisty','pelvistz','pelvistilt','pelvislist','pelvisrotation','lumbarextension','lumbarbending','lumbarrotation','hipflexionr','hipflexionl','hipadductionr','hipadductionl','hiprotationr','hiprotationl','kneeangler','kneeanglel','ankleangler','ankleanglel','armflexr','armflexl','armaddr','armaddl','armrotr','armrotl','elbowflexr','elbowflexl','prosupl','prosupr'});
